// <auto-generated />
using System;
using Hubtel.Wallets.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hubtel.Wallets.Api.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20230531154150_changedseeddata")]
    partial class changedseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hubtel.Wallets.Api.Models.Option", b =>
                {
                    b.Property<int>("PopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PopComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PopEntryPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("PopSysDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PopID");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            PopID = 1,
                            PopComment = "Type",
                            PopDesc = "Momo",
                            PopEntryPerson = "Erica",
                            PopNumber = 1,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 567, DateTimeKind.Local).AddTicks(5293)
                        },
                        new
                        {
                            PopID = 2,
                            PopComment = "Type",
                            PopDesc = "Card",
                            PopEntryPerson = "Erica",
                            PopNumber = 2,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6633)
                        },
                        new
                        {
                            PopID = 3,
                            PopComment = "Account Scheme",
                            PopDesc = "Visa",
                            PopEntryPerson = "Erica",
                            PopNumber = 3,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6674)
                        },
                        new
                        {
                            PopID = 4,
                            PopComment = "Account Scheme",
                            PopDesc = "Master Card",
                            PopEntryPerson = "Erica",
                            PopNumber = 4,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6677)
                        },
                        new
                        {
                            PopID = 5,
                            PopComment = "Account Scheme",
                            PopDesc = "MTN",
                            PopEntryPerson = "Erica",
                            PopNumber = 5,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6679)
                        },
                        new
                        {
                            PopID = 6,
                            PopComment = "Account Scheme",
                            PopDesc = "Vodafone",
                            PopEntryPerson = "Erica",
                            PopNumber = 6,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6681)
                        },
                        new
                        {
                            PopID = 7,
                            PopComment = "Account Scheme",
                            PopDesc = "AirtelTigo",
                            PopEntryPerson = "Erica",
                            PopNumber = 7,
                            PopSysDate = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(6683)
                        });
                });

            modelBuilder.Entity("Hubtel.Wallets.Api.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("Hubtel.Wallets.Api.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "john@lee.com",
                            RoleID = 2,
                            UserName = "John Lee"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "saray@ham.com",
                            RoleID = 1,
                            UserName = "Sarah Ham"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "mary@jes.com",
                            RoleID = 1,
                            UserName = "Mary Jes"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "erica@ana.com",
                            RoleID = 2,
                            UserName = "Erica Ana"
                        });
                });

            modelBuilder.Entity("Hubtel.Wallets.Api.Models.Wallet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountScheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountNumber = "0242567894",
                            AccountScheme = "MTN",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 568, DateTimeKind.Local).AddTicks(9633),
                            Name = "John Lee",
                            Owner = "0242567894",
                            Type = "Momo",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            AccountNumber = "0506665432",
                            AccountScheme = "Vodafone",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(2911),
                            Name = "John Lee",
                            Owner = "0554327654",
                            Type = "Momo",
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            AccountNumber = "467845",
                            AccountScheme = "Visa",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(3048),
                            Name = "John Lee",
                            Owner = "0207654326",
                            Type = "Card",
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            AccountNumber = "0207777775",
                            AccountScheme = "Vodafone",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(3061),
                            Name = "Sarah Ham",
                            Owner = "0206543276",
                            Type = "Momo",
                            UserID = 2
                        },
                        new
                        {
                            ID = 5,
                            AccountNumber = "234567",
                            AccountScheme = "Visa",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(3074),
                            Name = "Mary Jes",
                            Owner = "0267654327",
                            Type = "Card",
                            UserID = 3
                        },
                        new
                        {
                            ID = 6,
                            AccountNumber = "0275676548",
                            AccountScheme = "AirtelTigo",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(3086),
                            Name = "Sarah Ham",
                            Owner = "0267265438",
                            Type = "Momo",
                            UserID = 2
                        },
                        new
                        {
                            ID = 7,
                            AccountNumber = "999654",
                            AccountScheme = "Master Card",
                            CreatedAt = new DateTime(2023, 5, 31, 15, 41, 45, 628, DateTimeKind.Local).AddTicks(3097),
                            Name = "Erica Ana",
                            Owner = "0579876543",
                            Type = "Card",
                            UserID = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
